# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d4c400842a40e119169c8326e4f99769181f74da232a0ce7f1e3275172710abf474952dbb5c47f7e15aaacee47e14e5f81e4e3f8fe8300c460b52baadbc17e9

test:
  secret_key_base: eadc9f5477840b63c15ae13cb74c84a29606698a46a4a3dd3481cc14df66a4982285f3b22050558d6eca813315ae17fd6b83390e0fc82bbae6e75e88b29555f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
